<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Desain Kaos</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/5.3.1/fabric.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <style>
        .animate-spin {
            animation: spin 1s linear infinite;
        }

        @keyframes spin {
            from {
                transform: rotate(0deg);
            }

            to {
                transform: rotate(360deg);
            }
        }

        .animate-fade-in {
            animation: fade-in 0.5s ease-out forwards;
        }

        @keyframes fade-in {
            from {
                opacity: 0;
            }

            to {
                opacity: 1;
            }
        }
    </style>
</head>

<body class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 text-gray-800 font-sans">
    <header class="bg-white shadow">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold text-gray-900">Desain Kaos</h1>
        </div>
    </header>

    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <a href="/user/home"
            class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-all duration-300 transform hover:scale-105">
            <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                aria-hidden="true">
                <path fill-rule="evenodd"
                    d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z"
                    clip-rule="evenodd" />
            </svg>
            Kembali ke Home
        </a>
    </div>

    <div class="mx-auto">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div class="bg-white rounded-2xl shadow-xl overflow-hidden">
                <div class="grid grid-cols-1 lg:grid-cols-4">
                    {{-- Panel Kontrol --}}
                    <div class="bg-gradient-to-b from-blue-600 to-indigo-700 p-6 lg:p-8 text-white">
                        <h2 class="text-2xl font-bold mb-6 pb-3 border-b border-blue-500">
                            <i class="fas fa-paint-brush mr-2"></i>
                            Editor Desain
                        </h2>

                        <div class="space-y-6">
                            <div>
                                <h3 class="text-lg font-semibold mb-3 flex items-center">
                                    <i class="fas fa-upload mr-2"></i>
                                    Upload Desain
                                </h3>
                                <button id="upload-btn"
                                    class="w-full bg-white text-blue-600 hover:bg-blue-50 font-medium py-3 px-4 rounded-xl transition-all transform hover:scale-[1.02] shadow-md flex items-center justify-center">
                                    <i class="fas fa-image mr-2"></i>
                                    Upload Gambar/Logo
                                </button>
                                <input id="file-input" type="file" class="hidden" accept="image/*" />
                            </div>

                            <div class="pt-4 border-t border-blue-500">
                                <h3 class="text-lg font-semibold mb-3 flex items-center">
                                    <i class="fas fa-tshirt mr-2"></i>
                                    Warna Kaos
                                </h3>
                                <div id="color-options" class="grid grid-cols-3 gap-2">
                                    {{-- Buttons will be generated by JS --}}
                                </div>
                            </div>

                            <div class="pt-4 border-t border-blue-500">
                                <h3 class="text-lg font-semibold mb-3 flex items-center">
                                    <i class="fas fa-ruler mr-2"></i>
                                    Ukuran Kaos
                                </h3>
                                <select id="size-select"
                                    class="w-full bg-white/10 border border-blue-400 rounded-lg py-2 px-3 text-white focus:ring-2 focus:ring-blue-300 focus:border-blue-300 transition-colors">
                                    <option value="S">S - Rp 50,000</option>
                                    <option value="M">M - Rp 55,000</option>
                                    <option value="L">L - Rp 60,000</option>
                                    <option value="XL">XL - Rp 65,000</option>
                                    <option value="XXL">XXL - Rp 70,000</option>
                                </select>
                            </div>

                            <div class="p-4 bg-white/10 rounded-xl shadow-inner">
                                <p class="text-sm font-semibold">Total Harga:</p>
                                <p id="total-harga" class="text-2xl font-bold text-white">
                                    Rp 0
                                </p>
                            </div>

                            <button id="save-design-btn"
                                class="w-full bg-amber-500 hover:bg-amber-400 text-white font-medium py-3 px-4 rounded-xl transition-all transform hover:scale-[1.02] shadow-md flex items-center justify-center">
                                <i class="fas fa-download mr-2"></i>
                                Simpan Desain
                            </button>

                            <form id="order-form" class="pt-4 border-t border-blue-500 space-y-4">
                                <h3 class="text-lg font-semibold flex items-center">
                                    <i class="fas fa-paper-plane mr-2"></i>
                                    Kirim Pesanan
                                </h3>
                                <div>
                                    <label for="name" class="block text-sm font-medium mb-1">Nama</label>
                                    <input type="text" id="name-input" name="name" required
                                        class="w-full bg-white/10 border border-blue-400 rounded-lg py-2 px-3 text-white focus:ring-2 focus:ring-blue-300 focus:border-blue-300 transition-colors"
                                        placeholder="Nama lengkap" />
                                </div>
                                <div>
                                    <label for="email" class="block text-sm font-medium mb-1">Email</label>
                                    <input type="email" id="email-input" name="email" required
                                        class="w-full bg-white/10 border border-blue-400 rounded-lg py-2 px-3 text-white focus:ring-2 focus:ring-blue-300 focus:border-blue-300 transition-colors"
                                        placeholder="alamat@email.com" />
                                </div>
                                <button id="whatsapp-btn" type="button"
                                    class="w-full bg-green-500 hover:bg-green-400 text-white font-medium py-3 px-4 rounded-xl transition-all transform hover:scale-[1.02] shadow-md flex items-center justify-center">
                                    <i class="fab fa-whatsapp mr-2"></i>
                                    Pesan via WhatsApp
                                </button>
                            </form>
                        </div>
                    </div>

                    {{-- Tampilan Kanvas --}}
                    <div class="lg:col-span-3 flex flex-col items-center p-6 lg:p-8">
                        <div id="loading-spinner" class="absolute inset-0 flex items-center justify-center z-20 hidden">
                            <div
                                class="flex items-center space-x-3 bg-gray-900 text-white px-5 py-3 rounded-xl shadow-lg border border-gray-700 animate-fade-in">
                                <svg class="animate-spin h-5 w-5 text-indigo-400" xmlns="http://www.w3.org/2000/svg"
                                    fill="none" viewBox="0 0 24 24">
                                    <circle class="opacity-25" cx="12" cy="12" r="10"
                                        stroke="currentColor" stroke-width="4" />
                                    <path class="opacity-75" fill="currentColor"
                                        d="M4 12a8 8 0 018-8v4l3.5-3.5L12 0v4a8 8 0 010 16v4l3.5-3.5L12 20v4a8 8 0 01-8-8z" />
                                </svg>
                                <span class="text-sm font-medium">Memuat data...</span>
                            </div>
                        </div>

                        <div class="text-center mb-6">
                            <h1 class="text-3xl font-bold text-gray-800 mb-2">Desain Kaos Custom</h1>
                            <p class="text-gray-600 max-w-2xl">
                                Desain kaos impianmu dengan mudah! Seret dan lepas gambar ke area kaos yang diinginkan.
                            </p>
                        </div>

                        <div class="w-full bg-white p-6 mb-6">
                            <div
                                class="relative w-full h-[1500px] mx-auto rounded-xl overflow-hidden border-4 border-white shadow-lg">
                                <canvas id="mockup-canvas" width="400" height="400"></canvas>
                                <canvas id="design-canvas" class="absolute top-0 left-0 z-10 cursor-move" />
                            </div>
                        </div>

                        <div class="bg-blue-50 p-4 rounded-lg text-center max-w-2xl">
                            <p class="text-blue-700 flex items-center justify-center">
                                <i class="fas fa-lightbulb text-yellow-500 mr-2"></i>
                                Tips: Gunakan tool panel di sebelah kiri untuk menambahkan gambar dan mengubah warna
                                kaos.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        // State-like variables
        let designCanvas;
        let isLoading = true;
        let harga = 0;
        let size = "M";
        let userData = {
            name: '',
            email: ''
        };
        let activeColor = "putih";

        const tshirtColors = {
            putih: "#FFFFFF",
            hitam: "#000000",
            merah: "#E53E3E",
            biru: "#3182CE",
            hijau: "#38A169",
            abu: "#A0AEC0"
        };

        const mockupImages = {
            putih: {
                front: "/kaos/kaos-putih-depan.png",
                back: "/kaos/kaos-putih-belakang.png",
                side: "/kaos/kaos-putih-samping.png",
            },
            hitam: {
                front: "images/kaos-hitam-depan.png",
                back: "images/kaos-hitam-belakang.png",
                side: "images/kaos-hitam-samping.png",
            },
            merah: {
                front: "images/kaos-merah-depan.png",
                back: "images/kaos-merah-belakang.png",
                side: "images/kaos-merah-samping.png",
            },
            biru: {
                front: "images/kaos-biru-depan.png",
                back: "images/kaos-biru-belakang.png",
                side: "images/kaos-biru-samping.png",
            },
            hijau: {
                front: "images/kaos-hijau-depan.png",
                back: "images/kaos-hijau-belakang.png",
                side: "images/kaos-hijau-samping.png",
            },
            abu: {
                front: "images/kaos-abu-depan.png",
                back: "images/kaos-abu-belakang.png",
                side: "images/kaos-abu-samping.png",
            }
        };

        const sizePrices = {
            S: 50000,
            M: 55000,
            L: 60000,
            XL: 65000,
            XXL: 70000,
        };

        // DOM elements
        const fileInput = document.getElementById('file-input');
        const uploadBtn = document.getElementById('upload-btn');
        const sizeSelect = document.getElementById('size-select');
        const totalHargaElement = document.getElementById('total-harga');
        const colorOptionsDiv = document.getElementById('color-options');
        const saveDesignBtn = document.getElementById('save-design-btn');
        const nameInput = document.getElementById('name-input');
        const emailInput = document.getElementById('email-input');
        const whatsappBtn = document.getElementById('whatsapp-btn');
        const loadingSpinner = document.getElementById('loading-spinner');

        // --- FUNCTIONS ---

        const updateLoadingSpinner = (show) => {
            if (show) {
                loadingSpinner.classList.remove('hidden');
            } else {
                loadingSpinner.classList.add('hidden');
            }
        };

        const hitungHarga = () => {
            let total = sizePrices[size];
            if (!designCanvas) return;

            const allObjects = designCanvas.getObjects();
            allObjects.forEach(obj => {
                if (obj.type === "image" && !obj.isBackground) {
                    const width = obj.scaleX * obj.width;
                    const height = obj.scaleY * obj.height;
                    const area = width * height;

                    if (area < 10000) total += 20000;
                    else if (area < 30000) total += 35000;
                    else total += 50000;
                }
            });

            harga = total;
            totalHargaElement.innerText = `Rp ${harga.toLocaleString("id-ID")}`;
        };

        const loadTshirtImages = () => {
            if (!designCanvas) return;

            designCanvas.clear();
            updateLoadingSpinner(true);

            const loadImagesPromises = Object.keys(mockupImages[activeColor]).map((viewKey, index) => {
                return new Promise((resolve) => {
                    fabric.Image.fromURL(mockupImages[activeColor][viewKey], (img) => {
                        const scale = 0.5;
                        let top = 0;

                        if (viewKey === 'front') top = 250;
                        else if (viewKey === 'back') top = 750;
                        else if (viewKey === 'side') top = 1250;

                        img.set({
                            scaleX: scale,
                            scaleY: scale,
                            originX: "center",
                            originY: "center",
                            left: designCanvas.width / 2,
                            top: top,
                            selectable: false,
                            evented: false,
                            isBackground: true,
                            name: viewKey,
                        });
                        designCanvas.add(img);
                        designCanvas.sendToBack(img);
                        resolve();
                    }, {
                        crossOrigin: "anonymous"
                    });
                });
            });

            Promise.all(loadImagesPromises).then(() => {
                updateLoadingSpinner(false);
                designCanvas.renderAll();
            });
        };

        const addCustomControls = (obj) => {
            obj.controls.deleteControl = new fabric.Control({
                x: 0.5,
                y: -0.5,
                offsetY: -16,
                cursorStyle: "pointer",
                mouseUpHandler: (eventData, transform) => {
                    const target = transform.target;
                    designCanvas.remove(target);
                    designCanvas.requestRenderAll();
                    hitungHarga();
                    return true;
                },
                render: (ctx, left, top) => {
                    ctx.save();
                    ctx.translate(left, top);
                    ctx.fillStyle = "#FF4444";
                    ctx.beginPath();
                    ctx.arc(0, 0, 12, 0, Math.PI * 2);
                    ctx.fill();
                    ctx.strokeStyle = "white";
                    ctx.lineWidth = 2;
                    ctx.beginPath();
                    ctx.moveTo(-5, -5);
                    ctx.lineTo(5, 5);
                    ctx.moveTo(5, -5);
                    ctx.lineTo(-5, 5);
                    ctx.stroke();
                    ctx.restore();
                },
                cornerSize: 24,
            });
        };

        const handleLogoUpload = (e) => {
            const file = e.target.files[0];
            if (!file || !designCanvas) return;

            const reader = new FileReader();
            reader.onload = (f) => {
                fabric.Image.fromURL(
                    f.target.result,
                    (img) => {
                        if (!img) return;
                        img.scaleToWidth(150);
                        img.set({
                            left: 250,
                            top: 250,
                            originX: "center",
                            originY: "center",
                        });

                        addCustomControls(img);
                        designCanvas.add(img);
                        designCanvas.setActiveObject(img);
                        designCanvas.renderAll();
                        hitungHarga();
                    }, {
                        crossOrigin: "anonymous"
                    }
                );
            };
            reader.readAsDataURL(file);
        };

        const saveDesign = async () => {
            updateLoadingSpinner(true);
            try {
                const link = document.createElement("a");
                link.href = designCanvas.toDataURL("image/png");
                link.download = "desain-kaos-lengkap.png";
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
            } finally {
                updateLoadingSpinner(false);
            }
        };

        const sendToWhatsApp = async () => {
            if (!designCanvas) return;

            // Set userData from form inputs
            userData.name = nameInput.value;
            userData.email = emailInput.value;

            if (!userData.name || !userData.email) {
                alert('Mohon lengkapi nama dan email sebelum mengirim pesanan.');
                return;
            }

            const dataUrl = designCanvas.toDataURL("image/png");

            const blob = await (await fetch(dataUrl)).blob();
            const formData = new FormData();
            formData.append("design", blob, "design.png");

            try {
                const response = await fetch("/api/upload-design", {
                    method: "POST",
                    body: formData,
                    headers: {
                        'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')
                            .getAttribute('content')
                    }
                });

                const result = await response.json();
                const designUrl = result.url;

                const pesan =
                    `Halo, saya ingin memesan kaos custom:\n\n👤 Nama: ${userData.name}\n📧 Email: ${userData.email}\n📏 Ukuran: ${size}\n🎨 Warna Kaos: ${activeColor}\n💰 Total Harga: Rp ${harga.toLocaleString("id-ID")}\n\n📷 Preview desain: ${designUrl}\n\nTerima kasih 🙏`;

                const ADMIN_WHATSAPP = "6283114145264";
                const url = `https://wa.me/${ADMIN_WHATSAPP}?text=${encodeURIComponent(pesan)}`;
                window.open(url, "_blank");
            } catch (err) {
                console.error("Gagal upload desain:", err);
                alert("Upload desain gagal, coba lagi.");
            }
        };

        // --- INITIALIZATION ---

        const init = () => {
            designCanvas = new fabric.Canvas("design-canvas", {
                width: 500,
                height: 1500,
                preserveObjectStacking: true,
                backgroundColor: "#f8fafc",
            });

            // Register event listeners for the canvas AFTER it's been created
            designCanvas.on("object:added", hitungHarga);
            designCanvas.on("object:modified", hitungHarga);
            designCanvas.on("object:removed", hitungHarga);

            loadTshirtImages();
            hitungHarga();

            // Generate color buttons
            Object.entries(tshirtColors).forEach(([color, hex]) => {
                const button = document.createElement('button');
                button.className =
                    `h-10 rounded-lg border-2 transition-all ${activeColor === color ? 'border-white scale-110 shadow-lg' : 'border-blue-400'}`;
                button.style.backgroundColor = hex;
                button.title = color.charAt(0).toUpperCase() + color.slice(1);
                button.dataset.color = color;
                if (activeColor === color) {
                    button.innerHTML = '<i class="fas fa-check text-white"></i>';
                }
                colorOptionsDiv.appendChild(button);
            });
        };

        // --- EVENT LISTENERS ---

        uploadBtn.addEventListener('click', () => fileInput.click());
        fileInput.addEventListener('change', handleLogoUpload);
        sizeSelect.addEventListener('change', (e) => {
            size = e.target.value;
            hitungHarga();
        });
        colorOptionsDiv.addEventListener('click', (e) => {
            const button = e.target.closest('button');
            if (button) {
                const newColor = button.dataset.color;
                if (newColor && newColor !== activeColor) {
                    activeColor = newColor;

                    // Update active color class on all buttons
                    Array.from(colorOptionsDiv.children).forEach(btn => {
                        btn.classList.remove('border-white', 'scale-110', 'shadow-lg');
                        btn.classList.add('border-blue-400');
                        btn.innerHTML = '';
                    });
                    button.classList.add('border-white', 'scale-110', 'shadow-lg');
                    button.classList.remove('border-blue-400');
                    button.innerHTML = '<i class="fas fa-check text-white"></i>';

                    loadTshirtImages();
                }
            }
        });

        saveDesignBtn.addEventListener('click', saveDesign);
        whatsappBtn.addEventListener('click', sendToWhatsApp);

        init();
    });
</script>
</body>

</html>
